#!/bin/sh

case "$1" in
    getc)
	uci -c /usr/share/mico get version.version.CHANNEL
	;;
    getl)
	echo -e "current\nstable\nrelease"
	;;
    getn)
	if [ -f /tmp/state/version ]; then
	    uci -c /tmp/state/ get version.version.CHANNEL
	else
	    uci -c /usr/share/mico get version.version.CHANNEL
	fi
	;;
    setn)
	cp /usr/share/mico/version /tmp/state/
	uci -c /tmp/state set version.version.CHANNEL="$2"
	uci -c /tmp/state commit version
	;;
    *)
	echo -e "Usage: switch_channel <op> [channel]\n"\
	"getc\n"\
	"Get present channel.\n"\
	"getl\n"\
	"Get support channel list.\n"\
	"getn\n"\
	"Get next channel\n"\
	"setn\n"\
	"Swtich to channel"
esac
