#!/bin/sh /etc/rc.common

START=70

USE_PROCD=1


start_service() {
  mkdir -p /data/.mediaplayerconfig/DataBase/
  procd_open_instance
  procd_set_param command /usr/bin/alarmd

  procd_set_param respawn
  procd_append_param respawn 3600
  procd_append_param respawn 5
  procd_append_param respawn 5
  procd_close_instance
}

service_started() {
    #renice -n-5 -p
    true
}

stop_service() {
    killall -9 alarm 2>/dev/null >/dev/null
}
