#!/bin/sh /etc/rc.common

START=15
STOP=10

boot() {
    auen
    # set default volume and enable 
    alsactl -f /etc/asound.state restore
}

stop() {
    alsactl -f /data/status/asound.state store
}
