#!/bin/sh /etc/rc.common

#before wireless
START=51

USE_PROCD=1
DEBUG=0

start_service() {
  echo 0 > /sys/class/rfkill/rfkill0/state
  sleep 1
  echo 1 > /sys/class/rfkill/rfkill0/state
  sleep 1

  procd_open_instance
  if [ $DEBUG = "1" ]; then
      rm /tmp/btsnoop_.cfa > /dev/null 2>&1
      rm /tmp/bsa_.log > /dev/null 2>&1
      /usr/bin/bsa_server -d/dev/ttyS1 -r12 -pp /etc/bt/ -u/var/run/ -all=5 -b /tmp/btsnoop_.cfa > /tmp/bsa_.log &
  else
       procd_set_param command /usr/bin/bsa_server -d/dev/ttyS1 -r12 -pp /etc/bt/ -u /var/run/ --all=0
  fi
  procd_set_param respawn
  procd_append_param respawn 3600
  procd_append_param respawn 5
  procd_append_param respawn 5
  procd_close_instance

  procd_open_instance
  procd_set_param command /usr/bin/mibt_ble
  procd_set_param respawn
  procd_append_param respawn 3600
  procd_append_param respawn 5
  procd_append_param respawn 5
  procd_close_instance
}

restart() {
  killall -9 bsa_server 1>/dev/null 2>&1
  if [ $DEBUG = "1" ]; then
      mv /tmp/btsnoop_.cfa /tmp/btsnoop.cfa
      mv /tmp/bsa_.log /tmp/bsa.log
  fi
  stop
  start
}
