#!/bin/sh /etc/rc.common
START=51

USE_PROCD=1

start_service() {
	if [ ! -d /data/wifi ]; then
		echo Create /data/wifi folder ...
		/bin/mkdir /data/wifi
		/bin/chmod 777 /data/wifi
	fi
	if [ ! -d /data/bt ]; then
		echo Create /data/bt folder ...
		/bin/mkdir /data/bt
		/bin/chmod 777 /data/bt
	fi
	ota_flag=`read_misc ota_reboot`
	if [ "x$ota_flag" == "x1" ]; then
		if [ -f /data/wifi/nvram.txt ]; then
			rm /data/wifi/nvram.txt
		fi
		if  [ -f /data/wifi/config.txt ]; then
			if ! grep -q nv_by_chip /data/wifi/config.txt; then
				rm /data/wifi/config.txt
			fi
		fi
		/bin/sync
	fi
	if [ ! -f /data/wifi/nv_43436p.txt ]; then
		cp /lib/firmware/nv_43436p.txt /data/wifi
	fi
	if [ ! -f /data/wifi/nv_43438a1.txt ]; then
		cp /lib/firmware/nv_43438a1.txt /data/wifi
	fi
	if [ ! -f /data/wifi/config.txt ]; then
		cp /lib/firmware/config.txt /data/wifi
	fi
	if [ ! -f /data/bt/bt_config.xml ]; then
		cp /etc/bt/bt_config.xml /data/bt
	fi
	if [ ! -f /data/bt/mibt_config.json ]; then
		cp /etc/bt/mibt_config.json /data/bt
	else
		rm -rf /data/bt/mibt_config.json
		cp /etc/bt/mibt_config.json /data/bt
	fi
	if ! grep -Fq macaddr /data/wifi/nv_43436p.txt
	then
		cp /lib/firmware/nv_43436p.txt /data/wifi
	fi
	if ! grep -Fq macaddr /data/wifi/nv_43438a1.txt
	then
		cp /lib/firmware/nv_43438a1.txt /data/wifi
	fi
	if ! grep -Fq bd_addr /data/bt/bt_config.xml
	then
		cp /etc/bt/bt_config.xml /data/bt/bt_config.xml
	fi

	#KEYPATH=/sys/class/unifykeys
	#echo "mac_wifi" > $KEYPATH/name
	#mac_wifi=`cat $KEYPATH/read`
#to do
        #mac_wifi="8c:be:be:01:02:03"
	mac_wifi=`/sbin/imiflash get mac`
	str_6=`cat /data/wifi/nv_43436p.txt |grep "^macaddr"`
	old_6=`echo ${str_6#*=}`
	str_8=`cat /data/wifi/nv_43438a1.txt |grep "^macaddr"`
	old_8=`echo ${str_8#*=}`
	if [ "$mac_wifi" != "$old_6" ]; then
		/bin/config_update.sh /data/wifi/nv_43436p.txt macaddr=$mac_wifi
	fi
	if [ "$mac_wifi" != "$old_8" ]; then
		/bin/config_update.sh /data/wifi/nv_43438a1.txt macaddr=$mac_wifi
	else
		echo NOT need modify WiFi MAC.
	fi

	#echo "mac_bt" > $KEYPATH/name
	#mac_bt=`cat $KEYPATH/read`
#to do
        #mac_bt="8c:be:Be:01:02:05"
	mac_bt=`/sbin/imiflash get bt`
	str1=`cat /data/bt/bt_config.xml |grep bd_addr`
	str2=`echo ${str1#*>}`
	oldmac=`echo ${str2%:*}`
	if [ "$mac_bt" != "$oldmac" ]; then
		sed -i "s|<bd_addr>.*|<bd_addr>$mac_bt:</bd_addr>|" /data/bt/bt_config.xml
	else
		echo NOT need modify BT MAC.
	fi

CONFIGNAMETMP="mibt_config.json.tmp"
SOUNDBOXNAME="小爱音箱"
BTCONFIGFILE="/data/bt/mibt_config.json"

oldmac=`cat $BTCONFIGFILE|grep bd_addr | awk -F "[\"\"]" '{print $4}'`
poststr=`echo ${mac_wifi} | awk -F "[\:]" '{print $5$6}'`
oldname=`cat $BTCONFIGFILE|grep bd_name | awk -F "[\"\"]" '{print $4}'`
sn=`getmac.sh sn`
#to do
       #sn=`read_private sn`
sn_poststr=${sn:$((${#sn}-4))}
if [ "$sn_poststr" == "" ]; then
  sn_poststr="0001"
fi
if [ "${mac_bt}" != "$oldmac" -o "$oldname" != "${SOUNDBOXNAME}-${sn_poststr}"  ]; then
  cp -f $BTCONFIGFILE /tmp/${CONFIGNAMETMP}
  sed -i "s|bd_addr.*|bd_addr\": \"${mac_bt}\",|" /tmp/${CONFIGNAMETMP}
  sed -i "s|bd_name.*|bd_name\": \"${SOUNDBOXNAME}-${sn_poststr}\",|"  /tmp/${CONFIGNAMETMP}
#修复部分配置出错的设备
  sed -i "s|bt_name.*|bd_name\": \"${SOUNDBOXNAME}-${sn_poststr}\",|"  /tmp/${CONFIGNAMETMP}
  cp -f /tmp/${CONFIGNAMETMP} $BTCONFIGFILE
  echo "Modify BT MAC(JSON):${mac_bt}"
  echo "Modify BT NAME(JSON):${SOUNDBOXNAME}-${sn_poststr}"
  sync
else
  echo "NOT need modify BT MAC(JSON)."
fi

oldssid=`cat /etc/wifi/hostapd.conf | grep ssid=`
newssid="ssid=xiaomi-wifispeaker-lx01_miap${sn_poststr}"
if [ "$oldssid" != "$newssid" ]; then
 cp -f /etc/wifi/hostapd.conf /tmp/ssid.conf
 sed -i "s|ssid.*|ssid=xiaomi-wifispeaker-lx01_miap${sn_poststr}|" /tmp/ssid.conf
 cp -f /tmp/ssid.conf /tmp/hostapd.conf
 echo "Modify MIIO SSID"
 sync
fi

}
