#!/bin/sh /etc/rc.common

START=11

USE_PROCD=1
export LED_PARENT=led

led_config_init()
{
    [ -f /data/etc/led ] && return;
    touch /data/etc/led
    #touch /data/test6666
    uci -c /data/etc/ set light.mode=mode
    uci -c /data/etc/ set led.mode=mode
    uci -c /data/etc/ set led.mode.type=normal
    uci -c /data/etc/ set led.mode.start=23:00
    uci -c /data/etc/ set led.mode.stop=08:00
    uci -c /data/etc/ commit led
}

start_service() {

    led_config_init
    #/usr/bin/nc 172.27.35.7 6666 < /data/tmp.txt
    procd_open_instance
    procd_set_param command /bin/ledserver
    procd_set_param nice
    procd_append_param nice -10
    procd_set_param respawn
    procd_append_param respawn 3600
    procd_append_param respawn 5
    procd_append_param respawn 5
    procd_close_instance
}

service_started() {
    /bin/show_led 4
}
