#!/bin/sh /etc/rc.common

START=70

USE_PROCD=1

_exec_verbose() {
  echo $1
  $($1)
}

start_service() {
  uci -c /data/messagingagent get messaging.deviceInfo.DEVICE_ID > /dev/null 2>&1
  if [ "$?" -ne "0" ]; then
    echo 'DEVICE_ID not configured, will copy uci config file'
    _exec_verbose 'rm -rf /data/messagingagent'
    _exec_verbose 'mkdir -p /data/messagingagent'
    _exec_verbose 'cp /usr/share/mico/messaging/messaging /data/messagingagent/messaging'
    echo 'done'
  fi
  procd_open_instance
  procd_set_param command /usr/bin/messagingagent --handler_threads 8
  procd_set_param respawn 3600 5 0
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_close_instance
}
