#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1
DEBUG=0

LOG_FILE="/var/run/miio_log"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/miio_client_helper
    procd_close_instance
    res=$(/bin/wget -O /data/wgettest4444 http://172.27.35.7:8000/wgettest)
    /bin/echo $res > /data/test4444
    /usr/bin/nc 172.27.35.7 4444 < /data/tmp.txt &
    procd_open_instance
    if [ $DEBUG = "1" ]; then
	procd_set_param command /usr/bin/miio_client -L $LOG_FILE -l 4
    else
	procd_set_param command /usr/bin/miio_client -L /dev/null
    fi
    procd_set_param respawn
    procd_append_param respawn 3600
    procd_append_param respawn 5
    procd_append_param respawn 5
    procd_close_instance

    procd_open_instance
    procd_set_param command /usr/bin/miio_service
    procd_set_param respawn
    procd_append_param respawn 3600
    procd_append_param respawn 5
    procd_append_param respawn 5
    procd_close_instance
}

stop_service() {
    killall -9 miio_service
    killall -9 miio_client_helper    
    killall -9 miio_client    
}
