#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1
DEBUG=0

start_service() {
    mkdir /tmp/mico-voip/
    procd_open_instance
    procd_set_param command /usr/bin/quickplayer
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_set_param respawn
    procd_append_param respawn 3600
    procd_append_param respawn 5
    procd_append_param respawn 5
    procd_close_instance
}
