#!/bin/sh /etc/rc.common

START=72

USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/statpoints_daemon
  procd_set_param respawn 3600 5 0
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_close_instance
}
