#!/bin/sh /etc/rc.common

START=92

USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /bin/touchpad
  procd_set_param respawn
  procd_append_param respawn 3600
  procd_append_param respawn 5
  procd_append_param respawn 5
  procd_close_instance
}
