#!/bin/sh /etc/rc.common

START=61

USE_PROCD=1

MICO_SYSLOG_BINDDEVICE="[MICOREGISTER]"
export LED_PARENT=wireless

mico_log() {
    logger -t wireless -p 3 "${MICO_SYSLOG_BINDDEVICE} $*"
}


miio_service_start() {
   mico_log "miio enter ap config mode"
   touch "/tmp/need_dhcp_flag"
   echo -n /lib/firmware/fw_bcm4343_ag.bin > /sys/module/bcmdhd/parameters/firmware_path
   echo -n /data/wifi/ > /sys/module/bcmdhd/parameters/nvram_path
   echo -n 2 > /sys/module/bcmdhd/parameters/op_mode
   #sleep 1s
   /etc/init.d/dnsmasq restart
   hostapd /tmp/hostapd.conf &
   ifconfig wlan0 up
   ifconfig wlan0 10.0.0.1
   bssid=`matool_get_mac`
   wl down
   wl cur_etheraddr  $bssid
   wl up
   /etc/init.d/miio restart
   echo "ap mode"
}

miio_service_stop() {
   rm "/tmp/need_dhcp_flag" >/dev/null 2>&1
   killall hostapd  >/dev/null 2>&1
}


start_service() {
  [ ! -d "/data/wifi" ] && mkdir -p "/data/wifi"
  [ ! -f "/data/wifi/nv_43436p.txt" ] && cp /lib/firmware/nv_43436p.txt /data/wifi/
  [ ! -f "/data/wifi/nv_43438a1.txt" ] && cp /lib/firmware/nv_43438a1.txt /data/wifi/
  [ ! -f "/data/wifi/config.txt" ] && cp /lib/firmware/config.txt /data/wifi/config.txt

  dhd=`lsmod | grep bcmdhd`
  [ "$dhd" == "" ] && {
    insmod bcmdhd
  }
  show_led 6
#for ccmp error
  [ ! -f "/data/wifi/wpa_supplicant.conf" ] && {
      mico_log "mico enter ap config mode"
      ubus call mibt ble '{"action":"display"}'
      touch "/tmp/ap_config_mode_flag"
      [ ! -f "/data/status/config_done" ] && miio_service_start
      return 0
  }
  rm "/tmp/need_dhcp_flag" >/dev/null 2>&1
  echo -n /lib/firmware/fw_bcm4343_ag.bin > /sys/module/bcmdhd/parameters/firmware_path
  echo -n /data/wifi/ > /sys/module/bcmdhd/parameters/nvram_path
  echo -n 0 > /sys/module/bcmdhd/parameters/op_mode
  ifconfig wlan0 up

  key_mgmt=`cat /data/wifi/wpa_supplicant.conf | grep "key_mgmt="`
  open=`cat /data/wifi/wpa_supplicant.conf | grep "key_mgmt=NONE"`
  [ "$key_mgmt" == "" -a "$open" == "" ] && {
     sed -i "/psk=/a\  key_mgmt=WPA-PSK" /data/wifi/wpa_supplicant.conf
  }
  scan_ssid=`cat /data/wifi/wpa_supplicant.conf | grep "scan_ssid=1"`
  [ "$scan_ssid" == "" ] && {
     sed -i "/ssid=/a\  scan_ssid=1" /data/wifi/wpa_supplicant.conf
  }
  procd_open_instance
  procd_set_param command /usr/sbin/wpa_supplicant  -Dnl80211 -iwlan0 -c/data/wifi/wpa_supplicant.conf
  procd_set_param respawn
  procd_append_param respawn 3600
  procd_append_param respawn 5
  procd_append_param respawn 5
  procd_close_instance  


  procd_open_instance
  procd_set_param command /usr/sbin/wpa_cli -a/bin/wpa_action.sh
  procd_set_param respawn
  procd_append_param respawn 3600
  procd_append_param respawn 5
  procd_append_param respawn 5
  procd_close_instance

  /etc/init.d/dhcpc restart >/dev/null 2>&1

  return 0
}

stop_service() {

  killall wifi_check_ccmp.sh >/dev/null 2>&1
  miio_service_stop
#for ccmp error
  ifconfig wlan0 down
}

restart() {
  rm "/data/status/dhcp_done" >/dev/null 2>&1
  stop
  start
}
